import mirrorkey from 'mirrorkey';

export default mirrorkey([
  'FETCH_BEGIN',
  'FETCH_END',
  'EDIT_BEGIN',
  'EDIT_END',
  'MAINLINE_INFO_END',
  'MAINLINE_ASSIGN_OPERATOR_END',
  'MAINLINE_ADD_OPERATOR',
  'MAINLINE_FETCH_BUSINESS_HOURS',
  'MAINLINE_FETCH_BUSINNESS_HR_AND_TIMEZONE_EDIT_DETAILS'
]);
