import mirrorkey from 'mirrorkey';

export default mirrorkey([
  'FETCH_BEGIN',
  'FETCH_END',
  'EDIT_BEGIN',
  'EDIT_END',
  'FETCH_CALL_HANDLING_END',
  'FETCH_DEVICES_END',
  'FETCH_PROFILE_END',
  'FETCH_EDIT_USER_NAME_END',
  'EDIT_VOICE_PIN_END',
  'EDIT_PASSWORD_END',
  'DELETE_CALL_HANDLING_VM_END',
  'FETCH_SAFTY_END',
  'FETCH_SAFTY_DATA_FEILDS_END',
  'FETCH_YOUR_DEVICE_ADV_SETTINGS_END',
  'UPLOAD_CALL_HANDLING_AUDIO_BEGIN',
  'UPLOAD_ADV_CALL_HANDLING_AUDIO_BEGIN',
  'UPLOAD_AUDIO_END'
]);
